### ISSUE TITLE
Copy Edit

### ISSUE THREAD

**Issue by MissPhilbin** [raspberrypilearning/whoopi-cushion#1]
Added to comms request for copy edit.

**Comment by MissPhilbin** [comment]
@LornaLynch Are you happy for me to close this issue?

**Comment by LornaLynch** [comment]
Should be, though do we have to confirm with @LizUpton? I'm not sure if closing the issue here messes things up in Waffle.

**Comment by LizUpton** [comment]
This issue isn't on Waffle, so close away!

**Comment by MissPhilbin** [comment]
Closed with thanks.
